"""Python analyzers (spec 6.7-6.12, 8.5-8.18) and embedded extraction (spec 9).

Both analyzers declare ``needs="python_parse"`` and consume the
:class:`~stylog.parsers.python_native.PythonParseFacts` produced by
``parse_python``. All AST walks are iterative with explicit stacks; the parse
facts already guarantee raw nesting depth <= ``max_ast_nesting``.
"""

from __future__ import annotations

import ast
import keyword
import re
import tokenize
from dataclasses import dataclass
from typing import Literal

from stylog.analysis import build
from stylog.analysis.base import (
    PYTHON_AST_BACKEND,
    PYTHON_TOKENS_BACKEND,
    AnalyzerOutput,
    BaseAnalyzer,
    all_status_observations,
)
from stylog.analysis.identifiers import classify_style, split_components
from stylog.analysis.lines import scan_lines
from stylog.analysis.registry import (
    ANALYZER_CODE_PYTHON_AST,
    ANALYZER_CODE_PYTHON_TOKENS,
    features_owned_by,
)
from stylog.analysis.whitespace import is_white_space
from stylog.domain.artifact import SourcePosition, SourceSpan
from stylog.domain.diagnostic import Diagnostic, DiagnosticSeverity, make_diagnostic
from stylog.domain.feature import FeatureObservation, FeatureStatus
from stylog.parsers.python_native import (
    PYTHON_AST_PARSE_ERROR,
    PYTHON_AST_RESOURCE_LIMIT,
    PYTHON_ENCODING_ERROR,
    PYTHON_LOCATION_UNAVAILABLE,
    PythonParseFacts,
)
from stylog.runtime import AnalysisContext, RuntimeArtifact

_IGNORED_TOKEN_TYPES = frozenset(
    {
        tokenize.ENCODING,
        tokenize.ENDMARKER,
        tokenize.NL,
        tokenize.NEWLINE,
        tokenize.INDENT,
        tokenize.DEDENT,
        tokenize.COMMENT,
    }
)

_STRING_PREFIX_CATEGORIES = frozenset({"", "r", "u", "b", "br", "rb", "f", "fr", "rf"})

# Spec 8.11: every ast.AST instance except Module and the operator-ish bases.
_EXCLUDED_AST = (ast.Module, ast.operator, ast.unaryop, ast.boolop, ast.cmpop, ast.expr_context)

_TRY_STAR = getattr(ast, "TryStar", None)  # spec 8.13: only where the runtime exposes it
_MATCH = getattr(ast, "Match", None)

_TYPE_IGNORE_RE = re.compile(r"^type:\s*ignore(?:\[[^\]]+\])?\s*$")
_RUFF_NOQA_RE = re.compile(r"^ruff:\s*noqa\b", re.IGNORECASE)
_NOQA_RE = re.compile(r"^noqa(?:\s*:\s*[A-Z0-9_,\-\s]+)?$", re.IGNORECASE)
_FMT_RE = re.compile(r"^fmt:\s*(off|on|skip)\b", re.IGNORECASE)
_ISORT_RE = re.compile(r"^isort:\s*(skip|off|on|split)\b", re.IGNORECASE)
_ENCODING_COOKIE_RE = re.compile(r"^[ \t\f]*#.*coding[:=][ \t]*([-\w.]+)")
_GENERATED_PHRASES = ("do not edit", "auto-generated", "autogenerated")


def clean_comment(raw: str) -> str:
    """Comment cleaning per spec 9.1: drop exactly the first '#', then one U+0020."""
    text = raw.removeprefix("#")
    text = text.removeprefix(" ")
    return text


def _comment_markers(raw: str, row: int, column: int, line_content: str) -> list[str]:
    """Toolchain marker events for one COMMENT token (spec 9.7)."""
    markers: list[str] = []
    if row == 1 and column == 0 and raw.startswith("#!"):
        markers.append("shebang")
    if row in (1, 2) and _ENCODING_COOKIE_RE.match(line_content):
        markers.append("encoding_cookie")
    cleaned = clean_comment(raw)
    stripped = cleaned.strip(" \t")
    if _TYPE_IGNORE_RE.match(stripped):
        markers.append("type_ignore")
    if _RUFF_NOQA_RE.match(stripped):
        markers.append("ruff_noqa")
    if _NOQA_RE.match(stripped):
        markers.append("noqa")
    fmt = _FMT_RE.match(stripped)
    if fmt:
        markers.append(f"fmt_{fmt.group(1).lower()}")
    isort = _ISORT_RE.match(stripped)
    if isort:
        markers.append(f"isort_{isort.group(1).lower()}")
    lowered = stripped.lower()
    for tool in ("pylint", "mypy", "pyright"):
        if lowered.startswith(f"{tool}:"):
            markers.append(tool)
    if row <= 20:
        casefolded = cleaned.casefold()
        if "generated" in casefolded and any(p in casefolded for p in _GENERATED_PHRASES):
            markers.append("generated_notice")
    return markers


def _token_class(tok: tokenize.TokenInfo) -> str:
    ttype = tok.type
    if ttype == tokenize.NAME:
        if keyword.iskeyword(tok.string):
            return "keyword"
        if keyword.issoftkeyword(tok.string):
            return "soft_keyword"
        return "identifier"
    if ttype == tokenize.NUMBER:
        return "number"
    if ttype == tokenize.STRING:
        return "string"
    if tokenize.tok_name.get(ttype, "").startswith(("FSTRING_", "TSTRING_")):
        return "string_fragment"
    if ttype == tokenize.OP:
        return "operator"
    return "other"


def _number_form(spelling: str) -> str:
    """Number classification per spec 8.6 (case-insensitive exact spelling)."""
    text = spelling.lower()
    if text.endswith("j"):
        return "imaginary"
    if text.startswith("0x"):
        return "hexadecimal"
    if text.startswith("0o"):
        return "octal"
    if text.startswith("0b"):
        return "binary"
    if "." in text or "e" in text:
        return "floating"
    return "decimal_integer"


def _split_string_spelling(spelling: str) -> tuple[str, str]:
    """Return (prefix_category, quote) per spec 8.7 for a whole STRING token."""
    for index, char in enumerate(spelling):
        if char in ("'", '"'):
            triple = spelling[index : index + 3]
            quote = triple if triple in ("'''", '"""') else char
            prefix = spelling[:index].lower()
            if prefix not in _STRING_PREFIX_CATEGORIES:
                prefix = "other"
            return prefix, quote
    return "other", ""  # pragma: no cover - valid STRING tokens always contain a quote


def _byte_col_to_codepoint(line_content: str, byte_col: int) -> int:
    """Convert an AST UTF-8 byte column to a code-point column (spec 5.4)."""
    return len(line_content.encode("utf-8")[:byte_col].decode("utf-8"))


def _status_for_all(
    analyzer: BaseAnalyzer, status_value: FeatureStatus
) -> tuple[FeatureObservation, ...]:
    return all_status_observations(
        analyzer.analyzer_id, analyzer.implementation_version, status_value
    )


class PythonTokensAnalyzer(BaseAnalyzer):
    """Token-derived Python features (spec 6.7, 6.8, 6.11, 6.12, 8.5-8.7)."""

    analyzer_id = ANALYZER_CODE_PYTHON_TOKENS
    backend = PYTHON_TOKENS_BACKEND
    needs = "python_parse"

    def analyze(
        self,
        artifact: RuntimeArtifact,
        ctx: AnalysisContext,
        facts: object | None = None,
    ) -> AnalyzerOutput:
        if not ctx.config.analysis.code.python.enabled:
            return AnalyzerOutput(observations=_status_for_all(self, FeatureStatus.DISABLED))
        assert isinstance(facts, PythonParseFacts)
        if facts.decode_error_code is not None:
            diagnostic = make_diagnostic(
                PYTHON_ENCODING_ERROR,
                DiagnosticSeverity.ERROR,
                analyzer_id=self.analyzer_id,
                artifact_id=artifact.artifact_id,
            )
            return AnalyzerOutput(
                observations=_status_for_all(self, FeatureStatus.PARSER_ERROR),
                diagnostics=(diagnostic,),
            )
        if facts.token_error_code is not None:
            diagnostic = make_diagnostic(
                facts.token_error_code,
                DiagnosticSeverity.ERROR,
                analyzer_id=self.analyzer_id,
                artifact_id=artifact.artifact_id,
            )
            return AnalyzerOutput(
                observations=_status_for_all(self, FeatureStatus.PARSER_ERROR),
                diagnostics=(diagnostic,),
            )

        tokens = facts.tokens or []
        lines = scan_lines(facts.decoded_text) if facts.decoded_text is not None else []
        content_by_row = {line.row: line.content for line in lines}

        class_counts: dict[str, int] = {}
        keywords: dict[str, int] = {}
        operators: dict[str, int] = {}
        numbers: dict[str, int] = {}
        quotes: dict[str, int] = {}
        prefixes: dict[str, int] = {}
        identifier_lengths: list[int] = []
        identifier_styles: dict[str, int] = {}
        comment_lengths: list[int] = []
        comment_rows: set[int] = set()
        marker_counts: dict[str, int] = {}

        for tok in tokens:
            if tok.type == tokenize.COMMENT:
                row, column = tok.start
                comment_lengths.append(len(clean_comment(tok.string)))
                comment_rows.add(row)
                for marker in _comment_markers(
                    tok.string, row, column, content_by_row.get(row, "")
                ):
                    marker_counts[marker] = marker_counts.get(marker, 0) + 1
                continue
            if tok.type in _IGNORED_TOKEN_TYPES:
                continue
            category = _token_class(tok)
            class_counts[category] = class_counts.get(category, 0) + 1
            if category in ("keyword", "soft_keyword"):
                keywords[tok.string] = keywords.get(tok.string, 0) + 1
            elif category == "operator":
                operators[tok.string] = operators.get(tok.string, 0) + 1
            elif category == "number":
                form = _number_form(tok.string)
                numbers[form] = numbers.get(form, 0) + 1
            elif category == "string":
                prefix, quote = _split_string_spelling(tok.string)
                prefixes[prefix] = prefixes.get(prefix, 0) + 1
                quotes[quote] = quotes.get(quote, 0) + 1
            elif category == "identifier":
                identifier_lengths.append(len(tok.string))
                style = classify_style(tok.string)
                if style != "discard":
                    identifier_styles[style] = identifier_styles.get(style, 0) + 1

        comment_count = len(comment_lengths)
        observations: list[FeatureObservation] = []
        for fdef in features_owned_by(self.analyzer_id):
            fid = fdef.feature_id
            if fid == "code.python.lexical.token_class":
                obs = build.categorical_observation(fdef, self.analyzer_id, self.implementation_version, class_counts)
            elif fid == "code.python.lexical.keyword_distribution":
                obs = build.categorical_observation(fdef, self.analyzer_id, self.implementation_version, keywords)
            elif fid == "code.python.lexical.operator_distribution":
                obs = build.categorical_observation(fdef, self.analyzer_id, self.implementation_version, operators)
            elif fid == "code.python.lexical.number_form":
                obs = build.categorical_observation(fdef, self.analyzer_id, self.implementation_version, numbers)
            elif fid == "code.python.lexical.string_quote":
                obs = build.categorical_observation(fdef, self.analyzer_id, self.implementation_version, quotes)
            elif fid == "code.python.lexical.string_prefix":
                obs = build.categorical_observation(fdef, self.analyzer_id, self.implementation_version, prefixes)
            elif fid == "code.python.naming.identifier_occurrence_length":
                obs = build.histogram_observation(
                    fdef, self.analyzer_id, self.implementation_version, identifier_lengths
                )
            elif fid == "code.python.naming.identifier_occurrence_case_style":
                obs = build.categorical_observation(
                    fdef, self.analyzer_id, self.implementation_version, identifier_styles
                )
            elif fid == "code.python.comments.comment_count":
                obs = build.ok(
                    fdef,
                    self.analyzer_id,
                    self.implementation_version,
                    build.int_value(comment_count),
                    comment_count,
                )
            elif fid == "code.python.comments.comment_line_share":
                obs = build.ratio_observation(
                    fdef, self.analyzer_id, self.implementation_version, len(comment_rows), len(lines)
                )
            elif fid == "code.python.comments.comment_length":
                obs = build.histogram_observation(
                    fdef, self.analyzer_id, self.implementation_version, comment_lengths
                )
            elif fid == "code.toolchain.python_comment_marker":
                obs = build.categorical_observation(fdef, self.analyzer_id, self.implementation_version, marker_counts)
            else:  # pragma: no cover - registry drift guard
                raise AssertionError(f"unowned feature {fid}")
            observations.append(obs)
        return AnalyzerOutput(observations=tuple(observations))


def _collect_name_targets(node: ast.AST, role: str, events: list[tuple[str, str]]) -> None:
    """Recursively collect Name bindings through tuple/list/starred targets (8.10)."""
    stack = [node]
    while stack:
        current = stack.pop()
        if isinstance(current, ast.Name):
            events.append((current.id, role))
        elif isinstance(current, ast.Starred):
            stack.append(current.value)
        elif isinstance(current, (ast.Tuple, ast.List)):
            stack.extend(current.elts)
        # Attribute/Subscript/anything else: not a binding


def _own_scope_nodes(func: ast.FunctionDef | ast.AsyncFunctionDef) -> list[ast.AST]:
    """Nodes of a function body without descending into nested scopes (8.12)."""
    nodes: list[ast.AST] = []
    stack: list[ast.AST] = list(func.body)
    while stack:
        node = stack.pop()
        nodes.append(node)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Lambda)):
            continue
        stack.extend(ast.iter_child_nodes(node))
    return nodes


def _max_control_nesting(func: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    """Per-function control nesting maximum (spec 8.14). Body depth is 0."""
    max_depth = 0
    stack: list[tuple[ast.AST, int]] = [(stmt, 0) for stmt in func.body]
    while stack:
        node, depth = stack.pop()
        max_depth = max(max_depth, depth)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Lambda)):
            continue
        if isinstance(node, (ast.If, ast.For, ast.AsyncFor, ast.While)):
            stack.extend((child, depth + 1) for child in (*node.body, *node.orelse))
        elif isinstance(node, (ast.With, ast.AsyncWith)):
            stack.extend((child, depth + 1) for child in node.body)
        elif isinstance(node, ast.Try) or (_TRY_STAR is not None and isinstance(node, _TRY_STAR)):
            stack.extend((child, depth + 1) for child in (*node.body, *node.orelse, *node.finalbody))
            stack.extend((handler, depth + 1) for handler in node.handlers)
        elif isinstance(node, ast.ExceptHandler):
            stack.extend((child, depth) for child in node.body)
        elif _MATCH is not None and isinstance(node, _MATCH):
            stack.extend((case, depth + 1) for case in node.cases)
        elif isinstance(node, ast.match_case):
            stack.extend((child, depth) for child in node.body)
        else:
            stack.extend((child, depth) for child in ast.iter_child_nodes(node))
    return max_depth


def _branch_construct_count(own_nodes: list[ast.AST]) -> int:
    """Branch constructs in one function's own scope (spec 8.15)."""
    count = 0
    for node in own_nodes:
        if isinstance(node, (ast.If, ast.IfExp, ast.For, ast.AsyncFor, ast.While)) or isinstance(node, (ast.ExceptHandler, ast.match_case)):
            count += 1
        elif isinstance(node, ast.comprehension):
            count += 1 + len(node.ifs)
    return count


class PythonAstAnalyzer(BaseAnalyzer):
    """AST-derived Python features (spec 6.8-6.11, 8.8-8.18)."""

    analyzer_id = ANALYZER_CODE_PYTHON_AST
    backend = PYTHON_AST_BACKEND
    needs = "python_parse"

    def analyze(
        self,
        artifact: RuntimeArtifact,
        ctx: AnalysisContext,
        facts: object | None = None,
    ) -> AnalyzerOutput:
        if not ctx.config.analysis.code.python.enabled:
            return AnalyzerOutput(observations=_status_for_all(self, FeatureStatus.DISABLED))
        assert isinstance(facts, PythonParseFacts)
        if facts.ast_resource_limited:
            diagnostic = make_diagnostic(
                PYTHON_AST_RESOURCE_LIMIT,
                DiagnosticSeverity.WARNING,
                analyzer_id=self.analyzer_id,
                artifact_id=artifact.artifact_id,
            )
            return AnalyzerOutput(
                observations=_status_for_all(self, FeatureStatus.UNAVAILABLE),
                diagnostics=(diagnostic,),
            )
        failure_code = (
            facts.decode_error_code or facts.token_error_code or facts.ast_error_code
        )
        if failure_code is not None or facts.tree is None:
            diagnostic = make_diagnostic(
                failure_code or PYTHON_AST_PARSE_ERROR,
                DiagnosticSeverity.ERROR,
                analyzer_id=self.analyzer_id,
                artifact_id=artifact.artifact_id,
            )
            return AnalyzerOutput(
                observations=_status_for_all(self, FeatureStatus.PARSER_ERROR),
                diagnostics=(diagnostic,),
            )
        return self._analyze_tree(artifact, facts.tree)

    def _analyze_tree(self, artifact: RuntimeArtifact, tree: ast.Module) -> AnalyzerOutput:
        node_counts: dict[str, int] = {}
        edge_counts: dict[str, int] = {}
        depths: list[int] = []
        functions: list[ast.FunctionDef | ast.AsyncFunctionDef] = []
        classes: list[ast.ClassDef] = []
        control: dict[str, int] = {}
        assignments: dict[str, int] = {}
        import_kinds: dict[str, int] = {}
        alias_total = 0
        alias_with_asname = 0
        exceptions: dict[str, int] = {}
        comprehensions: dict[str, int] = {}
        match_case_counts: list[int] = []
        bindings: list[tuple[str, str]] = []
        attributes: list[str] = []
        docstrings: list[tuple[str, str]] = []

        module_doc = ast.get_docstring(tree, clean=True)
        if module_doc is not None:
            docstrings.append(("module", module_doc))

        stack: list[tuple[ast.AST, int]] = [(tree, 0)]
        while stack:
            node, depth = stack.pop()
            children = list(ast.iter_child_nodes(node))
            stack.extend((child, depth + 1) for child in children)
            if isinstance(node, _EXCLUDED_AST):
                continue
            node_name = type(node).__name__
            node_counts[node_name] = node_counts.get(node_name, 0) + 1
            depths.append(depth)
            for child in children:
                if not isinstance(child, _EXCLUDED_AST):
                    edge = f"{node_name}>{type(child).__name__}"
                    edge_counts[edge] = edge_counts.get(edge, 0) + 1

            if isinstance(node, ast.AsyncFunctionDef):
                functions.append(node)
                bindings.append((node.name, "async_function"))
            elif isinstance(node, ast.FunctionDef):
                functions.append(node)
                bindings.append((node.name, "function"))
            elif isinstance(node, ast.ClassDef):
                classes.append(node)
                bindings.append((node.name, "class"))

            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                kind = (
                    "class"
                    if isinstance(node, ast.ClassDef)
                    else ("async_function" if isinstance(node, ast.AsyncFunctionDef) else "function")
                )
                doc = ast.get_docstring(node, clean=True)
                if doc is not None:
                    docstrings.append((kind, doc))

            # Control constructs (8.13).
            if isinstance(node, ast.If):
                control["if"] = control.get("if", 0) + 1
            elif isinstance(node, ast.IfExp):
                control["if_expression"] = control.get("if_expression", 0) + 1
            elif isinstance(node, ast.For):
                control["for"] = control.get("for", 0) + 1
                _collect_name_targets(node.target, "loop_target", bindings)
            elif isinstance(node, ast.AsyncFor):
                control["async_for"] = control.get("async_for", 0) + 1
                _collect_name_targets(node.target, "loop_target", bindings)
            elif isinstance(node, ast.While):
                control["while"] = control.get("while", 0) + 1
            elif _TRY_STAR is not None and isinstance(node, _TRY_STAR):
                control["try_star"] = control.get("try_star", 0) + 1
            elif isinstance(node, ast.Try):
                control["try"] = control.get("try", 0) + 1
            elif isinstance(node, ast.With):
                control["with"] = control.get("with", 0) + 1
            elif isinstance(node, ast.AsyncWith):
                control["async_with"] = control.get("async_with", 0) + 1
            elif _MATCH is not None and isinstance(node, _MATCH):
                control["match"] = control.get("match", 0) + 1
                match_case_counts.append(len(node.cases))
            elif isinstance(node, ast.ListComp):
                control["list_comprehension"] = control.get("list_comprehension", 0) + 1
                comprehensions["list"] = comprehensions.get("list", 0) + 1
            elif isinstance(node, ast.SetComp):
                control["set_comprehension"] = control.get("set_comprehension", 0) + 1
                comprehensions["set"] = comprehensions.get("set", 0) + 1
            elif isinstance(node, ast.DictComp):
                control["dict_comprehension"] = control.get("dict_comprehension", 0) + 1
                comprehensions["dict"] = comprehensions.get("dict", 0) + 1
            elif isinstance(node, ast.GeneratorExp):
                control["generator_expression"] = control.get("generator_expression", 0) + 1
                comprehensions["generator"] = comprehensions.get("generator", 0) + 1

            # Assignments (6.10) and their binding targets (8.10).
            if isinstance(node, ast.Assign):
                assignments["assign"] = assignments.get("assign", 0) + 1
                for target in node.targets:
                    _collect_name_targets(target, "assignment", bindings)
            elif isinstance(node, ast.AnnAssign):
                assignments["ann_assign"] = assignments.get("ann_assign", 0) + 1
                _collect_name_targets(node.target, "assignment", bindings)
            elif isinstance(node, ast.AugAssign):
                assignments["aug_assign"] = assignments.get("aug_assign", 0) + 1
                _collect_name_targets(node.target, "assignment", bindings)
            elif isinstance(node, ast.NamedExpr):
                assignments["named_expr"] = assignments.get("named_expr", 0) + 1
                _collect_name_targets(node.target, "walrus", bindings)

            # Imports (6.10, 8.10, 8.17).
            if isinstance(node, ast.Import):
                import_kinds["import"] = import_kinds.get("import", 0) + 1
                for alias in node.names:
                    alias_total += 1
                    if alias.asname is not None:
                        alias_with_asname += 1
                        bindings.append((alias.asname, "import_binding"))
                    else:
                        bindings.append((alias.name.split(".", 1)[0], "import_binding"))
            elif isinstance(node, ast.ImportFrom):
                import_kinds["import_from"] = import_kinds.get("import_from", 0) + 1
                for alias in node.names:
                    alias_total += 1
                    if alias.asname is not None:
                        alias_with_asname += 1
                    if alias.name != "*":
                        bindings.append((alias.asname or alias.name, "import_binding"))

            # Exception constructs (8.16).
            if isinstance(node, ast.Try):
                exceptions["try"] = exceptions.get("try", 0) + 1
                if node.finalbody:
                    exceptions["finally_block"] = exceptions.get("finally_block", 0) + 1
            elif _TRY_STAR is not None and isinstance(node, _TRY_STAR):
                exceptions["try_star"] = exceptions.get("try_star", 0) + 1
                if node.finalbody:
                    exceptions["finally_block"] = exceptions.get("finally_block", 0) + 1
            elif isinstance(node, ast.ExceptHandler):
                exceptions["except_handler"] = exceptions.get("except_handler", 0) + 1
                if node.type is None:
                    exceptions["bare_except"] = exceptions.get("bare_except", 0) + 1
                if node.name:
                    bindings.append((node.name, "exception_target"))
            elif isinstance(node, ast.Raise):
                exceptions["raise"] = exceptions.get("raise", 0) + 1

            # Remaining binding events (8.10).
            if isinstance(node, ast.arguments):
                for arg in node.posonlyargs:
                    bindings.append((arg.arg, "parameter_posonly"))
                for arg in node.args:
                    bindings.append((arg.arg, "parameter_positional"))
                for arg in node.kwonlyargs:
                    bindings.append((arg.arg, "parameter_kwonly"))
                if node.vararg is not None:
                    bindings.append((node.vararg.arg, "parameter_vararg"))
                if node.kwarg is not None:
                    bindings.append((node.kwarg.arg, "parameter_kwarg"))
            elif isinstance(node, ast.comprehension):
                _collect_name_targets(node.target, "comprehension_target", bindings)
            elif isinstance(node, ast.withitem):
                if node.optional_vars is not None:
                    _collect_name_targets(node.optional_vars, "with_target", bindings)
            elif isinstance(node, ast.MatchAs) or isinstance(node, ast.MatchStar):
                if node.name is not None:
                    bindings.append((node.name, "pattern_binding"))
            elif isinstance(node, ast.MatchMapping):
                if node.rest is not None:
                    bindings.append((node.rest, "pattern_binding"))

            if isinstance(node, ast.Attribute):
                attributes.append(node.attr)

        # Per-function measurements (8.12, 8.14, 8.15).
        function_kinds: dict[str, int] = {}
        function_lengths: list[int] = []
        parameter_counts: list[int] = []
        return_counts: list[int] = []
        nonterminal_returns = 0
        max_nestings: list[int] = []
        branch_counts: list[int] = []
        diagnostics: list[Diagnostic] = []
        for func in functions:
            kind = "async" if isinstance(func, ast.AsyncFunctionDef) else "sync"
            function_kinds[kind] = function_kinds.get(kind, 0) + 1
            if func.lineno is None or func.end_lineno is None:
                diagnostics.append(
                    make_diagnostic(
                        PYTHON_LOCATION_UNAVAILABLE,
                        DiagnosticSeverity.WARNING,
                        analyzer_id=self.analyzer_id,
                        feature_id="code.python.structure.function_length_lines",
                        artifact_id=artifact.artifact_id,
                    )
                )
            else:
                function_lengths.append(func.end_lineno - func.lineno + 1)
            args = func.args
            parameter_counts.append(
                len(args.posonlyargs)
                + len(args.args)
                + len(args.kwonlyargs)
                + (1 if args.vararg is not None else 0)
                + (1 if args.kwarg is not None else 0)
            )
            own_nodes = _own_scope_nodes(func)
            returns = [n for n in own_nodes if isinstance(n, ast.Return)]
            return_counts.append(len(returns))
            statement_ends = [
                n.end_lineno
                for n in own_nodes
                if isinstance(n, ast.stmt) and n.end_lineno is not None
            ]
            if statement_ends:
                max_end = max(statement_ends)
                if any(r.end_lineno is not None and r.end_lineno < max_end for r in returns):
                    nonterminal_returns += 1
            max_nestings.append(_max_control_nesting(func))
            branch_counts.append(_branch_construct_count(own_nodes))

        decorator_counts = [len(func.decorator_list) for func in functions]
        decorator_counts.extend(len(cls.decorator_list) for cls in classes)

        binding_roles: dict[str, int] = {}
        binding_lengths: list[int] = []
        binding_styles: dict[str, int] = {}
        binding_component_lengths: list[int] = []
        for name, role in bindings:
            binding_roles[role] = binding_roles.get(role, 0) + 1
            binding_lengths.append(len(name))
            style = classify_style(name)
            if style != "discard":
                binding_styles[style] = binding_styles.get(style, 0) + 1
            for component in split_components(name):
                binding_component_lengths.append(len(component))

        attribute_lengths = [len(attr) for attr in attributes]
        attribute_styles: dict[str, int] = {}
        for attr in attributes:
            style = classify_style(attr)
            if style != "discard":
                attribute_styles[style] = attribute_styles.get(style, 0) + 1

        docstring_kinds: dict[str, int] = {}
        docstring_lengths: list[int] = []
        for kind, text in docstrings:
            docstring_kinds[kind] = docstring_kinds.get(kind, 0) + 1
            docstring_lengths.append(len(text))

        function_total = len(functions)
        class_total = len(classes)

        observations: list[FeatureObservation] = []
        for fdef in features_owned_by(self.analyzer_id):
            fid = fdef.feature_id
            aid = self.analyzer_id
            version = self.implementation_version
            if fid == "code.python.syntax.node_distribution":
                obs = build.categorical_observation(fdef, aid, version, node_counts)
            elif fid == "code.python.syntax.parent_child_distribution":
                obs = build.categorical_observation(fdef, aid, version, edge_counts)
            elif fid == "code.python.syntax.node_depth":
                obs = build.histogram_observation(fdef, aid, version, depths)
            elif fid == "code.python.structure.function_count":
                obs = build.ok(fdef, aid, version, build.int_value(function_total), 1)
            elif fid == "code.python.structure.class_count":
                obs = build.ok(fdef, aid, version, build.int_value(class_total), 1)
            elif fid == "code.python.structure.function_kind":
                obs = build.categorical_observation(fdef, aid, version, function_kinds)
            elif fid == "code.python.structure.function_length_lines":
                obs = build.histogram_observation(fdef, aid, version, function_lengths)
            elif fid == "code.python.structure.parameter_count":
                obs = build.histogram_observation(fdef, aid, version, parameter_counts)
            elif fid == "code.python.structure.return_count":
                obs = build.histogram_observation(fdef, aid, version, return_counts)
            elif fid == "code.python.structure.nonterminal_return_function_share":
                obs = build.ratio_observation(fdef, aid, version, nonterminal_returns, function_total)
            elif fid == "code.python.structure.control_construct":
                obs = build.categorical_observation(fdef, aid, version, control)
            elif fid == "code.python.structure.max_control_nesting":
                obs = build.histogram_observation(fdef, aid, version, max_nestings)
            elif fid == "code.python.structure.branch_construct_count":
                obs = build.histogram_observation(fdef, aid, version, branch_counts)
            elif fid == "code.python.structure.decorator_count":
                obs = build.histogram_observation(fdef, aid, version, decorator_counts)
            elif fid == "code.python.structure.assignment_kind":
                obs = build.categorical_observation(fdef, aid, version, assignments)
            elif fid == "code.python.structure.import_kind":
                obs = build.categorical_observation(fdef, aid, version, import_kinds)
            elif fid == "code.python.structure.import_alias_share":
                obs = build.ratio_observation(fdef, aid, version, alias_with_asname, alias_total)
            elif fid == "code.python.structure.exception_construct":
                obs = build.categorical_observation(fdef, aid, version, exceptions)
            elif fid == "code.python.structure.comprehension_kind":
                obs = build.categorical_observation(fdef, aid, version, comprehensions)
            elif fid == "code.python.structure.match_case_count":
                obs = build.histogram_observation(fdef, aid, version, match_case_counts)
            elif fid == "code.python.naming.binding_role":
                obs = build.categorical_observation(fdef, aid, version, binding_roles)
            elif fid == "code.python.naming.binding_length":
                obs = build.histogram_observation(fdef, aid, version, binding_lengths)
            elif fid == "code.python.naming.binding_case_style":
                obs = build.categorical_observation(fdef, aid, version, binding_styles)
            elif fid == "code.python.naming.binding_component_length":
                obs = build.histogram_observation(fdef, aid, version, binding_component_lengths)
            elif fid == "code.python.naming.attribute_name_length":
                obs = build.histogram_observation(fdef, aid, version, attribute_lengths)
            elif fid == "code.python.naming.attribute_case_style":
                obs = build.categorical_observation(fdef, aid, version, attribute_styles)
            elif fid == "code.python.comments.docstring_kind":
                obs = build.categorical_observation(fdef, aid, version, docstring_kinds)
            elif fid == "code.python.comments.docstring_length":
                obs = build.histogram_observation(fdef, aid, version, docstring_lengths)
            else:  # pragma: no cover - registry drift guard
                raise AssertionError(f"unowned feature {fid}")
            observations.append(obs)
        return AnalyzerOutput(observations=tuple(observations), diagnostics=tuple(diagnostics))


@dataclass(frozen=True)
class EmbeddedCandidate:
    """One embedded prose candidate before fingerprinting (spec 9)."""

    kind: Literal["comment_block", "inline_comment", "docstring"]
    text: str
    span: SourceSpan
    ordinal: int
    docstring_owner: str | None = None


def extract_embedded(
    artifact: RuntimeArtifact, facts: PythonParseFacts, config: object
) -> list[EmbeddedCandidate]:
    """Extract embedded comment/docstring prose candidates (spec 9).

    Comment exclusions follow 9.2 (shebang, encoding cookie, toolchain
    markers, whitespace-only). Comment blocks group per 9.4. Token failure
    suppresses comment candidates; AST failure suppresses docstrings.
    """
    python_config = config.analysis.code.python
    if not python_config.embedded_text or facts.decoded_text is None:
        return []
    lines = scan_lines(facts.decoded_text)
    content_by_row = {line.row: line.content for line in lines}
    found: list[tuple[str, str, SourceSpan, str | None]] = []

    if facts.tokens is not None:
        comments: list[tuple[int, int, int, str, bool]] = []
        for tok in facts.tokens:
            if tok.type != tokenize.COMMENT:
                continue
            row, column = tok.start  # tokenize columns are code-point based
            end_column = tok.end[1]
            cleaned = clean_comment(tok.string)
            if _comment_markers(tok.string, row, column, content_by_row.get(row, "")):
                continue
            if all(is_white_space(char) for char in cleaned):
                continue
            prefix_text = content_by_row.get(row, "")[:column]
            full_line = all(char in " \t" for char in prefix_text)
            comments.append((row, column, end_column, cleaned, full_line))

        block: list[tuple[int, int, int, str, bool]] = []

        def flush_block() -> None:
            if not block:
                return
            text = "\n".join(entry[3] for entry in block)
            span = SourceSpan(
                start=SourcePosition(line=block[0][0], column=block[0][1]),
                end=SourcePosition(line=block[-1][0], column=block[-1][2]),
            )
            found.append(("comment_block", text, span, None))
            block.clear()

        for entry in comments:
            row, column, end_column, cleaned, full_line = entry
            if not full_line:
                flush_block()
                span = SourceSpan(
                    start=SourcePosition(line=row, column=column),
                    end=SourcePosition(line=row, column=end_column),
                )
                found.append(("inline_comment", cleaned, span, None))
            elif block and row == block[-1][0] + 1 and column == block[0][1]:
                block.append(entry)
            else:
                flush_block()
                block.append(entry)
        flush_block()

    if facts.tree is not None:
        doc_nodes: list[tuple[str, ast.AST]] = [("module", facts.tree)]
        stack: list[ast.AST] = [facts.tree]
        while stack:
            node = stack.pop()
            if isinstance(node, ast.ClassDef):
                doc_nodes.append((f"class:{node.name}", node))
            elif isinstance(node, ast.AsyncFunctionDef):
                doc_nodes.append((f"async_function:{node.name}", node))
            elif isinstance(node, ast.FunctionDef):
                doc_nodes.append((f"function:{node.name}", node))
            stack.extend(ast.iter_child_nodes(node))
        for owner, node in doc_nodes:
            doc = ast.get_docstring(node, clean=True)
            if doc is None:
                continue
            expr = node.body[0]  # the docstring expression statement
            start_line = content_by_row.get(expr.lineno, "")
            end_line = content_by_row.get(expr.end_lineno or expr.lineno, "")
            span = SourceSpan(
                start=SourcePosition(
                    line=expr.lineno,
                    column=_byte_col_to_codepoint(start_line, expr.col_offset),
                ),
                end=SourcePosition(
                    line=expr.end_lineno or expr.lineno,
                    column=_byte_col_to_codepoint(end_line, expr.end_col_offset or 0),
                ),
            )
            found.append(("docstring", doc, span, owner))

    found.sort(key=lambda item: (item[2].start.line, item[2].start.column))
    found = found[: python_config.max_embedded_artifacts]
    ordinals = {"comment_block": 0, "inline_comment": 0, "docstring": 0}
    candidates: list[EmbeddedCandidate] = []
    for kind, text, span, owner in found:
        ordinals[kind] += 1
        candidates.append(
            EmbeddedCandidate(
                kind=kind,  # type: ignore[arg-type]
                text=text,
                span=span,
                ordinal=ordinals[kind],
                docstring_owner=owner,
            )
        )
    return candidates
