"""Python token analyzer tests (spec 6.7, 6.8, 6.11, 6.12, 8.5-8.7, 9.1, 9.7, 25.7, 25.9)."""

from __future__ import annotations

import hashlib
import sys

from stylog.analysis.identifiers import classify_style, split_components
from stylog.analysis.python import PythonTokensAnalyzer
from stylog.analysis.registry import ANALYZER_CODE_PYTHON_TOKENS, features_owned_by
from stylog.config import (
    AnalysisConfig,
    CodeAnalysisConfig,
    PythonAnalysisConfig,
    StylogConfig,
)
from stylog.domain.artifact import ArtifactKind
from stylog.domain.provenance import current_runtime_signature
from stylog.parsers.python_native import parse_python
from stylog.runtime import AnalysisContext, ResourceHandles, RuntimeArtifact

FIXTURE_25_7 = (
    "import os as operating_system\n"
    "\n"
    "async def fetch(myURL2: str, *, retries=3):\n"
    "    if retries > 0:\n"
    '        return f"{myURL2=}"\n'
    "    return None  # noqa\n"
)

STRING_SRC = (
    "a = 'x'\n"
    'b = "y"\n'
    "c = '''z'''\n"
    'd = """w"""\n'
    "e = r'raw'\n"
    "f = b'bytes'\n"
    "g = rb'rb'\n"
    "h = BR'br'\n"
    "i = u'str'\n"
    "j = fr'fr'\n"
    "k = Rf'rf'\n"
    "l = 'it\\'s'\n"
)

NUMBER_SRC = (
    "a = 1\n"
    "b = 1_000\n"
    "c = 0xFF\n"
    "d = 0o17\n"
    "e = 0b101\n"
    "f = 3.14\n"
    "g = 1e5\n"
    "h = 1.5j\n"
    "i = 2J\n"
    "j = .5\n"
    "k = 5.\n"
)

MARKER_SRC = (
    "#!/usr/bin/env python\n"
    "# -*- coding: utf-8 -*-\n"
    "# Generated by tool. Do not edit.\n"
    "x = 1  # type: ignore[attr-defined]\n"
    "y = 2  # noqa\n"
    "z = 3  # noqa: F401, W503\n"
    "w = 4  # ruff: noqa\n"
    "# fmt: on\n"
    "# isort: skip\n"
    "# pylint: disable=too-few-public-methods\n"
    "# mypy: strict\n"
    "# pyright: basic\n"
)


def make_artifact(src: str) -> RuntimeArtifact:
    raw = src.encode("utf-8")
    return make_artifact_bytes(raw, src)


def make_artifact_bytes(raw: bytes, text: str = "") -> RuntimeArtifact:
    return RuntimeArtifact(
        artifact_id="t",
        kind=ArtifactKind.CODE,
        language="python",
        encoding="utf-8",
        raw_bytes=raw,
        text=text,
        content_sha256=hashlib.sha256(raw).hexdigest(),
    )


def make_ctx(config: StylogConfig | None = None) -> AnalysisContext:
    return AnalysisContext(
        config=config or StylogConfig(),
        runtime=current_runtime_signature(),
        resources=ResourceHandles(),
    )


def by_id(output):
    return {obs.feature_id: obs for obs in output.observations}


def cat(obs) -> dict[str, int]:
    return {entry.key: entry.count for entry in obs.value.counts}


def hist(obs) -> dict[int, int]:
    return {point.point: point.count for point in obs.value.points}


def run_tokens(src: str, config: StylogConfig | None = None):
    ctx = make_ctx(config)
    artifact = make_artifact(src)
    facts = parse_python(artifact, ctx.config)
    return PythonTokensAnalyzer().analyze(artifact, ctx, facts)


# --- spec 25.7 token fixture ---


def test_25_7_token_class():
    out = by_id(run_tokens(FIXTURE_25_7))
    assert cat(out["code.python.lexical.token_class"]) == {
        "identifier": 8,
        "keyword": 8,
        "number": 2,
        "operator": 13,
        "string_fragment": 2,
    }


def test_25_7_keyword_distribution():
    out = by_id(run_tokens(FIXTURE_25_7))
    assert cat(out["code.python.lexical.keyword_distribution"]) == {
        "None": 1,
        "as": 1,
        "async": 1,
        "def": 1,
        "if": 1,
        "import": 1,
        "return": 2,
    }


def test_25_7_operator_distribution():
    out = by_id(run_tokens(FIXTURE_25_7))
    assert cat(out["code.python.lexical.operator_distribution"]) == {
        "(": 1,
        ")": 1,
        "*": 1,
        ",": 2,
        ":": 3,
        "=": 2,
        ">": 1,
        "{": 1,
        "}": 1,
    }


def test_25_7_number_form():
    out = by_id(run_tokens(FIXTURE_25_7))
    assert cat(out["code.python.lexical.number_form"]) == {"decimal_integer": 2}


def test_25_7_identifier_occurrences():
    out = by_id(run_tokens(FIXTURE_25_7))
    assert hist(out["code.python.naming.identifier_occurrence_length"]) == {
        2: 1,   # os
        3: 1,   # str
        5: 1,   # fetch
        6: 2,   # myURL2 twice
        7: 2,   # retries twice
        16: 1,  # operating_system
    }
    assert cat(out["code.python.naming.identifier_occurrence_case_style"]) == {
        "camel_lower": 2,
        "lower": 5,
        "snake_lower": 1,
    }


def test_25_7_myurl2_split_and_style():
    assert split_components("myURL2") == ["my", "URL2"]
    assert classify_style("myURL2") == "camel_lower"


def test_25_7_comment_features_and_noqa_marker():
    out = by_id(run_tokens(FIXTURE_25_7))
    assert out["code.python.comments.comment_count"].value.value == 1
    share = out["code.python.comments.comment_line_share"].value
    assert (share.numerator, share.denominator) == (1, 7)
    assert hist(out["code.python.comments.comment_length"]) == {4: 1}  # "noqa"
    assert cat(out["code.toolchain.python_comment_marker"]) == {"noqa": 1}


def test_25_7_fstring_fragments_are_not_string_tokens():
    out = by_id(run_tokens(FIXTURE_25_7))
    # f"{myURL2=}" produces FSTRING_* fragments only; no whole STRING token exists
    assert out["code.python.lexical.string_quote"].status == "insufficient_support"
    assert out["code.python.lexical.string_prefix"].status == "insufficient_support"


def test_registry_coverage_sorted():
    out = run_tokens(FIXTURE_25_7)
    owned = [f.feature_id for f in features_owned_by(ANALYZER_CODE_PYTHON_TOKENS)]
    assert [o.feature_id for o in out.observations] == sorted(owned)


# --- spec 8.6 / 8.7 ---


def test_number_forms():
    out = by_id(run_tokens(NUMBER_SRC))
    assert cat(out["code.python.lexical.number_form"]) == {
        "binary": 1,
        "decimal_integer": 2,
        "floating": 4,
        "hexadecimal": 1,
        "imaginary": 2,
        "octal": 1,
    }


def test_string_quote_and_prefix():
    out = by_id(run_tokens(STRING_SRC))
    # j = fr'fr' and k = Rf'rf' are f-strings: FSTRING_* fragments, never whole
    # STRING tokens, so they do not participate in quote/prefix (spec 8.7)
    assert cat(out["code.python.lexical.token_class"])["string_fragment"] == 6
    assert cat(out["code.python.lexical.string_quote"]) == {
        "'": 7,
        '"': 1,
        "'''": 1,
        '"""': 1,
    }
    assert cat(out["code.python.lexical.string_prefix"]) == {
        "": 5,
        "b": 1,
        "br": 1,
        "r": 1,
        "rb": 1,
        "u": 1,
    }


def test_tstring_and_fstring_fragments():
    out = by_id(run_tokens('t"Hi {x}"\nf"{y}"\n'))
    if sys.version_info >= (3, 14):
        expected = {
            "identifier": 2,
            "operator": 4,
            "string_fragment": 5,
        }
    else:
        # cpython.tokenize before 3.14 has no TSTRING_* tokens: t"Hi {x}"
        # lexes as NAME 't' followed by a plain STRING.
        expected = {
            "identifier": 2,
            "operator": 2,
            "string": 1,
            "string_fragment": 2,
        }
    assert cat(out["code.python.lexical.token_class"]) == expected


def test_soft_keywords():
    out = by_id(run_tokens("match = 1\ncase = 2\n_ = 3\n"))
    assert cat(out["code.python.lexical.token_class"]) == {
        "number": 3,
        "operator": 3,
        "soft_keyword": 3,
    }
    assert cat(out["code.python.lexical.keyword_distribution"]) == {
        "_": 1,
        "case": 1,
        "match": 1,
    }
    # soft keywords are not identifier occurrences
    assert out["code.python.naming.identifier_occurrence_length"].status == "insufficient_support"


# --- spec 9.1 / 9.7 markers ---


def test_comment_cleaning_lengths():
    out = by_id(run_tokens("#x\n# x\n#  x\n#\n"))
    # cleaned per 9.1: "x", "x", " x", "" -> lengths 1, 1, 2, 0
    assert hist(out["code.python.comments.comment_length"]) == {0: 1, 1: 2, 2: 1}
    assert out["code.python.comments.comment_count"].value.value == 4


def test_marker_vocabulary():
    out = by_id(run_tokens(MARKER_SRC))
    assert cat(out["code.toolchain.python_comment_marker"]) == {
        "encoding_cookie": 1,
        "fmt_on": 1,
        "generated_notice": 1,
        "isort_skip": 1,
        "mypy": 1,
        "noqa": 2,
        "pylint": 1,
        "pyright": 1,
        "ruff_noqa": 1,
        "shebang": 1,
        "type_ignore": 1,
    }


def test_generated_notice_first_20_lines_only():
    src_on20 = "\n" * 19 + "# auto-generated. do not edit\n"
    out = by_id(run_tokens(src_on20))
    assert cat(out["code.toolchain.python_comment_marker"]) == {"generated_notice": 1}
    src_on21 = "\n" * 20 + "# auto-generated. do not edit\n"
    out = by_id(run_tokens(src_on21))
    assert out["code.toolchain.python_comment_marker"].status == "insufficient_support"


def test_no_markers_insufficient():
    out = by_id(run_tokens("x = 1  # plain comment\n"))
    assert out["code.toolchain.python_comment_marker"].status == "insufficient_support"


def test_comment_line_share_unique_rows():
    out = by_id(run_tokens("x = 1  # a\ny = 2  # b\n"))
    share = out["code.python.comments.comment_line_share"].value
    assert (share.numerator, share.denominator) == (2, 3)


# --- failure semantics (spec 8.1, 8.4, 25.9) ---


def test_tokenize_failure_is_atomic():
    ctx = make_ctx()
    artifact = make_artifact("def f(")
    facts = parse_python(artifact, ctx.config)
    assert facts.token_error_code == "PYTHON_TOKENIZE_ERROR"
    assert facts.tokens is None
    assert facts.tree is None
    out = PythonTokensAnalyzer().analyze(artifact, ctx, facts)
    assert all(o.status == "parser_error" for o in out.observations)
    assert len(out.observations) == len(features_owned_by(ANALYZER_CODE_PYTHON_TOKENS))
    assert [d.code for d in out.diagnostics] == ["PYTHON_TOKENIZE_ERROR"]


def test_ast_failure_keeps_token_features():
    out = by_id(run_tokens("x = 1\nif:\n    pass\n"))
    assert out["code.python.lexical.token_class"].status == "ok"


def test_decode_error_conflict():
    raw = b"\xef\xbb\xbf# coding: latin-1\nx = 1\n"
    ctx = make_ctx()
    artifact = make_artifact_bytes(raw)
    facts = parse_python(artifact, ctx.config)
    assert facts.decode_error_code == "PYTHON_ENCODING_ERROR"
    assert facts.tokens is None and facts.tree is None
    out = PythonTokensAnalyzer().analyze(artifact, ctx, facts)
    assert all(o.status == "parser_error" for o in out.observations)
    assert [d.code for d in out.diagnostics] == ["PYTHON_ENCODING_ERROR"]


def test_latin1_cookie_decodes():
    raw = "# coding: latin-1\nx = 'café'\n".encode("latin-1")
    ctx = make_ctx()
    artifact = make_artifact_bytes(raw)
    facts = parse_python(artifact, ctx.config)
    assert facts.decode_error_code is None
    assert facts.encoding == "iso-8859-1"
    assert facts.tokens is not None and facts.tree is not None


def test_utf8_bom_accepted():
    raw = b"\xef\xbb\xbfx = 1\n"
    ctx = make_ctx()
    artifact = make_artifact_bytes(raw)
    facts = parse_python(artifact, ctx.config)
    assert facts.decode_error_code is None
    assert facts.encoding == "utf-8-sig"


def test_python_disabled():
    config = StylogConfig(
        analysis=AnalysisConfig(
            code=CodeAnalysisConfig(python=PythonAnalysisConfig(enabled=False))
        )
    )
    out = run_tokens("x = 1\n", config)
    assert all(o.status == "disabled" for o in out.observations)


def test_empty_source():
    out = by_id(run_tokens(""))
    assert out["code.python.lexical.token_class"].status == "insufficient_support"
    assert out["code.python.comments.comment_count"].value.value == 0
    assert out["code.python.comments.comment_line_share"].status == "insufficient_support"
