"""Portable scientific domain models.

These strict Pydantic v2 models are Stylog's interchange contract. They never
import parser, NLP, dataframe, numeric-array, CLI, or infrastructure machinery.
"""

from stylog.domain._base import HexDigest64, PortableModel
from stylog.domain.artifact import (
    ArtifactDescriptor,
    ArtifactKind,
    ContentIdentity,
    ContentIdentitySha256,
    ContentIdentitySuppressed,
    EmbeddedArtifactDescriptor,
    SourcePosition,
    SourceSpan,
)
from stylog.domain.baseline import (
    Baseline,
    BaselineCompatibility,
    BaselineDescriptor,
    BaselineFeature,
)
from stylog.domain.benchmark import (
    BenchmarkResult,
    BenchmarkSplitRealization,
    PairwiseFeatureMetrics,
    RiskEntry,
    TransformationFeatureDistance,
)
from stylog.domain.diagnostic import (
    Diagnostic,
    DiagnosticContextEntry,
    DiagnosticSeverity,
    diagnostic_sort_key,
    make_diagnostic,
    sort_diagnostics,
)
from stylog.domain.evidence import (
    AggregateObservation,
    AggregationKind,
    EvidenceAggregate,
    EvidenceMember,
    EvidenceSet,
    LinkageDescriptor,
    MissingStatusCount,
)
from stylog.domain.feature import (
    CategoricalDistributionValue,
    CategoryCount,
    DisabledObservation,
    FeatureObservation,
    FeatureStatus,
    FeatureValue,
    FloatValue,
    InsufficientSupportObservation,
    IntegerValue,
    NotApplicableObservation,
    OkFeatureObservation,
    OrderedHistogramValue,
    ParserErrorObservation,
    PointCount,
    RatioValue,
    SummaryStatisticsValue,
    Support,
    UnavailableObservation,
)
from stylog.domain.fingerprint import AnalysisBundle, EmbeddedAnalysis, Fingerprint
from stylog.domain.interpretation import (
    Comparison,
    ComparisonComponent,
    ComparisonFamily,
    Profile,
    ProfileObservation,
)
from stylog.domain.provenance import (
    AnalyzerSignature,
    BackendSignature,
    ModelSignature,
    PackageProvenance,
    ParserGrammarSignature,
    ResourceSignature,
    RuntimeSignature,
    current_runtime_signature,
)
from stylog.domain.representation import (
    DenseVectorValue,
    Representation,
    RepresentationFit,
    RepresentationResourceSignature,
    RepresentationValue,
    SparseCoordinate,
    SparseVectorValue,
)
from stylog.domain.verification import (
    Verification,
    VerifierCalibration,
    VerifierEligibility,
    VerifierFeature,
    VerifierFit,
    VerifierFitConfig,
    VerifierPairPolicy,
    VerifierThresholds,
)

__all__ = [
    "AggregateObservation",
    "AggregationKind",
    "AnalysisBundle",
    "AnalyzerSignature",
    "ArtifactDescriptor",
    "ArtifactKind",
    "BackendSignature",
    "Baseline",
    "BaselineCompatibility",
    "BaselineDescriptor",
    "BaselineFeature",
    "BenchmarkResult",
    "BenchmarkSplitRealization",
    "CategoricalDistributionValue",
    "CategoryCount",
    "Comparison",
    "ComparisonComponent",
    "ComparisonFamily",
    "ContentIdentity",
    "ContentIdentitySha256",
    "ContentIdentitySuppressed",
    "DenseVectorValue",
    "Diagnostic",
    "DiagnosticContextEntry",
    "DiagnosticSeverity",
    "DisabledObservation",
    "EmbeddedAnalysis",
    "EmbeddedArtifactDescriptor",
    "EvidenceAggregate",
    "EvidenceMember",
    "EvidenceSet",
    "FeatureObservation",
    "FeatureStatus",
    "FeatureValue",
    "Fingerprint",
    "FloatValue",
    "HexDigest64",
    "InsufficientSupportObservation",
    "IntegerValue",
    "LinkageDescriptor",
    "MissingStatusCount",
    "ModelSignature",
    "NotApplicableObservation",
    "OkFeatureObservation",
    "OrderedHistogramValue",
    "PackageProvenance",
    "PairwiseFeatureMetrics",
    "ParserErrorObservation",
    "ParserGrammarSignature",
    "PointCount",
    "PortableModel",
    "Profile",
    "ProfileObservation",
    "RatioValue",
    "Representation",
    "RepresentationFit",
    "RepresentationResourceSignature",
    "RepresentationValue",
    "ResourceSignature",
    "RiskEntry",
    "RuntimeSignature",
    "SourcePosition",
    "SourceSpan",
    "SparseCoordinate",
    "SparseVectorValue",
    "SummaryStatisticsValue",
    "Support",
    "TransformationFeatureDistance",
    "UnavailableObservation",
    "Verification",
    "VerifierCalibration",
    "VerifierEligibility",
    "VerifierFeature",
    "VerifierFit",
    "VerifierFitConfig",
    "VerifierPairPolicy",
    "VerifierThresholds",
    "current_runtime_signature",
    "diagnostic_sort_key",
    "make_diagnostic",
    "sort_diagnostics",
]

# Single source of truth: portable ``schema`` literal -> strict model type.
# Consumers with a narrower supported set derive filtered views of this dict.
PORTABLE_MODELS_BY_SCHEMA: dict[str, type[PortableModel]] = {
    "stylog.fingerprint": Fingerprint,
    "stylog.analysis": AnalysisBundle,
    "stylog.comparison": Comparison,
    "stylog.profile": Profile,
    "stylog.evidence-aggregate": EvidenceAggregate,
    "stylog.evidence-set": EvidenceSet,
    "stylog.baseline": Baseline,
    "stylog.representation": Representation,
    "stylog.representation-fit": RepresentationFit,
    "stylog.benchmark-result": BenchmarkResult,
    "stylog.verifier-fit": VerifierFit,
    "stylog.verification": Verification,
}
